# =============================================================================
# Database — Postgres on RDS, deployed into the VPC's database subnets.
#
# Architecture, from outermost to innermost:
#
#   ┌─ VPC (10.0.0.0/16)
#   │   ┌─ database subnets (10.0.20.0/24, 10.0.21.0/24, no NAT route)
#   │   │   ┌─ DB subnet group (created by the VPC module in Phase 2)
#   │   │   │   ┌─ aws_db_instance.main
#   │   │   │   │   - postgres 16.13, db.t3.micro, single-AZ
#   │   │   │   │   - encrypted at rest, no public access
#   │   │   │   │   - master DB "giftgauge"; per-env DBs created by the
#   │   │   │   │     Helm migration job at deploy time
#   │   │   │   └─ ...
#   │   │   └─ aws_security_group.rds (5432 from VPC CIDR for now;
#   │   │      narrowed to EKS node SG in Phase 4)
#   │   └─ ...
#   └─ ...
#
# Master credentials are generated by Terraform and stored in Secrets Manager.
# Apps read them via External Secrets Operator (Phase 5/6); Terraform never
# bakes the password into a values file.
# =============================================================================

# -----------------------------------------------------------------------------
# Master password — generated once, kept stable for the life of the instance.
# -----------------------------------------------------------------------------
resource "random_password" "rds_master" {
  length  = 32
  special = true

  # RDS Postgres rejects '/', '@', '"', and ' ' in master passwords.
  override_special = "!#$%^&*()-_=+[]{}<>?"
}

# -----------------------------------------------------------------------------
# Secrets Manager — single secret holding everything an app needs to connect.
#
# `recovery_window_in_days = 0` means immediate deletion on destroy. In prod
# you'd set this to 7-30 so a fat-finger destroy is recoverable. In our lab
# we destroy/re-create regularly and a recovery window prevents reusing the
# secret name on the next apply, which is annoying.
# -----------------------------------------------------------------------------
resource "aws_secretsmanager_secret" "rds_master" {
  name                    = "${var.project_name}/rds/master"
  description             = "RDS master credentials for ${var.project_name}."
  recovery_window_in_days = 0

  tags = {
    Component = "database"
  }
}

resource "aws_secretsmanager_secret_version" "rds_master" {
  secret_id = aws_secretsmanager_secret.rds_master.id

  # JSON shape chosen to match what External Secrets Operator templates
  # naturally produce. Apps will see env vars like DB_HOST, DB_USER etc.
  secret_string = jsonencode({
    username = var.rds_master_username
    password = random_password.rds_master.result
    engine   = "postgres"
    host     = aws_db_instance.main.address
    port     = aws_db_instance.main.port
    dbname   = aws_db_instance.main.db_name
  })
}

# -----------------------------------------------------------------------------
# Security group — 5432/tcp from the VPC.
#
# Phase 4 will narrow this to "from the EKS node security group only" so RDS
# isn't reachable from anything else that lands in the VPC (e.g. a debug EC2).
# Doing it now would create a chicken-and-egg with EKS, so we widen
# temporarily. Documented in docs/decisions.md.
# -----------------------------------------------------------------------------
resource "aws_security_group" "rds" {
  name        = "${var.project_name}-rds"
  description = "Postgres ingress for ${var.project_name} from inside the VPC."
  vpc_id      = module.vpc.vpc_id

  tags = {
    Component = "database"
  }
}

resource "aws_vpc_security_group_ingress_rule" "rds_from_vpc" {
  security_group_id = aws_security_group.rds.id

  description = "Postgres from anywhere inside the VPC. Narrowed in Phase 4."
  cidr_ipv4   = module.vpc.vpc_cidr_block
  ip_protocol = "tcp"
  from_port   = 5432
  to_port     = 5432
}

# RDS does not initiate outbound connections, so no egress rule needed.

# -----------------------------------------------------------------------------
# Custom parameter group — slow-query logging.
#
# Useful for the chaos defense. If the instructor breaks something with a
# slow query, this writes the offending statement to CloudWatch Logs where
# we can grep it.
# -----------------------------------------------------------------------------
resource "aws_db_parameter_group" "main" {
  name        = "${var.project_name}-postgres16"
  family      = "postgres16"
  description = "Custom parameters for ${var.project_name}: slow query logging."

  parameter {
    name  = "log_min_duration_statement"
    value = "1000" # log any statement running more than 1 second
  }

  parameter {
    name  = "log_connections"
    value = "1"
  }

  parameter {
    name  = "log_disconnections"
    value = "1"
  }

  tags = {
    Component = "database"
  }
}

# -----------------------------------------------------------------------------
# The RDS instance itself.
# -----------------------------------------------------------------------------
resource "aws_db_instance" "main" {
  identifier = "${var.project_name}-postgres"

  # ----- Engine -----
  engine                     = "postgres"
  engine_version             = var.rds_engine_version
  auto_minor_version_upgrade = false # pinned for reproducibility

  # ----- Instance sizing -----
  instance_class = var.rds_instance_class

  # ----- Storage -----
  allocated_storage     = var.rds_allocated_storage
  max_allocated_storage = var.rds_max_allocated_storage # autoscale ceiling
  storage_type          = "gp3"
  storage_encrypted     = true

  # ----- DB setup -----
  db_name  = var.rds_master_db_name # "giftgauge" — per-env DBs created at deploy time
  username = var.rds_master_username
  password = random_password.rds_master.result
  port     = 5432

  # ----- Networking -----
  db_subnet_group_name   = module.vpc.database_subnet_group_name
  vpc_security_group_ids = [aws_security_group.rds.id]
  publicly_accessible    = false

  # ----- HA -----
  multi_az = false # single-AZ for budget; documented trade-off

  # ----- Backups -----
  backup_retention_period   = 7
  backup_window             = "03:00-04:00"
  copy_tags_to_snapshot     = true
  delete_automated_backups  = true # lab convenience
  skip_final_snapshot       = true # lab convenience; PROD would NEVER skip
  final_snapshot_identifier = null

  # ----- Maintenance window (Mondays 04-05 UTC) -----
  maintenance_window = "Mon:04:00-Mon:05:00"

  # ----- Monitoring -----
  performance_insights_enabled          = true
  performance_insights_retention_period = 7 # 7 days = free tier
  enabled_cloudwatch_logs_exports       = ["postgresql"]
  # Enhanced Monitoring (monitoring_interval / monitoring_role_arn) is
  # deliberately omitted — it requires a custom IAM role we cannot create
  # in the lab (LabRole has no iam:PassRole for it).

  # ----- Parameter group -----
  parameter_group_name = aws_db_parameter_group.main.name

  # ----- Lifecycle -----
  deletion_protection = false # lab convenience
  apply_immediately   = true  # lab convenience; prod would batch into windows

  tags = {
    Component = "database"
    Engine    = "postgres"
  }
}
