apiVersion: v2
name: giftgauge
description: GiftGauge — privacy-preserving gift scoring application

type: application

version: 0.1.0
appVersion: "0.1.0"

maintainers:
  - name: Justin Pyne
    email: jpyne.justin@gmail.com
