# =============================================================================
# UAT environment overrides.
#
# Used as: helm upgrade --install giftgauge ./helm/giftgauge \
#          --namespace uat -f envs/uat/values.yaml
# =============================================================================

global:
  environment: uat
  imageTag: v0.1.3

ingress:
  host: uat.justinpyne.xyz

database:
  envDbName: giftgauge_uat

services:
  frontend:
    replicas: 1
    nodegroup: ""
  profile:
    replicas: 1
    nodegroup: ""
  sharing:
    replicas: 1
    nodegroup: ""
  scoring:
    replicas: 1
    nodegroup: ""
