# =============================================================================
# prod-green environment.
#
# Other half of the prod blue/green pair. Active when global.activeColor=green.
# =============================================================================

global:
  environment: prod-green
  color: green
  imageTag: v0.1.7

ingress:
  host: app.justinpyne.xyz
  tlsSecretName: prod-app-tls
  shadowHost: prod-green.justinpyne.xyz
  shadowTlsSecretName: prod-green-shadow-tls

database:
  envDbName: giftgauge_prod

services:
  frontend:
    replicas: 1
    nodegroup: ""
  profile:
    replicas: 1
    nodegroup: ""
  sharing:
    replicas: 1
    nodegroup: ""
  scoring:
    replicas: 1
    nodegroup: ""
